# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  milestone:
    types: [created]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.milestoneName }}
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.milestoneName }}
