# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release tag (e.g. 1.5.0)'
        required: true
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: Create release branch
      run: git checkout -b release/${{ github.event.inputs.name }}
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.name }}
      
    - name: Trigger my downstream workflow
      run: |
          curl -XPOST -u "${{ secrets.GIT_CREDENTIALS }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/path/to/workflow.yml/dispatches --data '{"ref":"master" }'

